services:
  test-service:
    build: .
    network_mode: host
    container_name: test-service
    environment:
      - DUMMY_VAR=dummyvar
      - AUTHSERVICE_INTEGRATION=${AUTHSERVICE_INTEGRATION}
      - EMAILSERVICE_INTEGRATION=${EMAILSERVICE_INTEGRATION}
      - FILESERVICE_INTEGRATION=${FILESERVICE_INTEGRATION}
      - GATEWAYSERVICE_INTEGRATION=${GATEWAYSERVICE_INTEGRATION}
      - REACTSERVICE_INTEGRATION=${REACTSERVICE_INTEGRATION}
      - TELEMETRYSERVICE_INTEGRATION=${TELEMETRYSERVICE_INTEGRATION}
      - VAULTSERVICE_INTEGRATION=${VAULTSERVICE_INTEGRATION}
      - BOOTSTRAP_TOKEN=${BOOTSTRAP_TOKEN}
      - SERVICE_SECRET_TEST=${SERVICE_SECRET_TEST}
      - SERVICE_SECRET_AUTH=${SERVICE_SECRET_AUTH}
      - SERVICE_SECRET_EMAIL=${SERVICE_SECRET_EMAIL}
      - INITIAL_SUPER_CREDENTIALS_FILE=/bootstrap/initial-super-user.txt
      - AUTH_BASE_URL=${AUTH_BASE_URL}
      - GATEWAY_BASE_URL=${GATEWAY_BASE_URL}
      - EMAIL_BASE_URL=${EMAIL_BASE_URL}
      - MAILDEV_BASE_URL=${MAILDEV_BASE_URL}
      - REACT_BASE_URL=${REACT_BASE_URL}
      - FILE_BASE_URL=${FILE_BASE_URL}
      - VAULT_BASE_URL=${VAULT_BASE_URL}
      - TELEMETRY_BASE_URL=${TELEMETRY_BASE_URL}
    volumes:
      - ./test-results:/testservice/test-results
      - ${INITIAL_SUPER_CREDENTIALS_DIRECTORY:-/tmp}:/bootstrap:ro
networks:
  shared-network:
    external: true
