services:
  test-service:
    build: .
    network_mode: host
    container_name: test-service
    environment:
      - DUMMY_VAR=dummyvar
      - BOOTSTRAP_TOKEN=${BOOTSTRAP_TOKEN} # Integration line: Vault
      - SERVICE_SECRET_TEST=${SERVICE_SECRET_TEST} # Integration line: Auth
      - SERVICE_SECRET_AUTH=${SERVICE_SECRET_AUTH} # Integration line: Auth
      - SERVICE_SECRET_EMAIL=${SERVICE_SECRET_EMAIL} # Integration line: Auth
      - INITIAL_SUPER_CREDENTIALS_FILE=/bootstrap/initial-super-user.txt # Integration line: Auth
      - AUTH_BASE_URL=${AUTH_BASE_URL} # Integration line: Auth
      - EMAIL_BASE_URL=${EMAIL_BASE_URL} # Integration line: Email
      - MAILDEV_BASE_URL=${MAILDEV_BASE_URL} # Integration line: Email
      - REACT_BASE_URL=${REACT_BASE_URL} # Integration line: React
      - FILE_BASE_URL=${FILE_BASE_URL} # Integration line: File
      - VAULT_BASE_URL=${VAULT_BASE_URL} # Integration line: Vault
      - TELEMETRY_BASE_URL=${TELEMETRY_BASE_URL} # Integration line: Telemetry
    volumes:
      - ./test-results:/testservice/test-results
      - ${INITIAL_SUPER_CREDENTIALS_DIRECTORY}:/bootstrap:ro # Integration line: Auth
networks:
  shared-network:
    external: true
